# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-08 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Criterium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('characteristics', models.ManyToManyField(blank=True, to='classification.Characteristic')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('criteria', models.ManyToManyField(blank=True, to='classification.Criterium')),
            ],
        ),
        migrations.CreateModel(
            name='InteractiveSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reference', models.CharField(max_length=500)),
                ('abstract', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='characteristic',
            name='interactive_systems',
            field=models.ManyToManyField(blank=True, to='classification.InteractiveSystem'),
        ),
    ]
